name: Zason
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43721
title: Zason
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff80'
    - '#000000'
    - '#808080'
    - '#8f2c2a'
    - '#00ffff'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
